import { GlassPanel } from "@/components/ui/glass-panel";
import { StatusPill } from "@/components/ui/status-pill";
import { FileCheck, CheckCircle, AlertTriangle } from "lucide-react";
import type { AuditReport, PaymentPlan } from "@/lib/api/types";

interface AuditReportProps {
  report: AuditReport;
  plan: PaymentPlan;
}

export function AuditReport({ report, plan }: AuditReportProps) {
  const approvedCount = report.transactions.length;
  const totalExecuted = report.transactions.reduce((sum, t) => sum + t.amount, 0);

  const blockedWallets = report.riskCheck.checks.whitelistCheck.blockedWallets ?? [];
  const blockedItems = plan.items.filter((item) =>
    blockedWallets.includes(item.recipient.walletAddress)
  );
  const blockedCount = blockedItems.length;
  const blockedAmount = blockedItems.reduce((sum, item) => sum + item.amount, 0);

  return (
    <GlassPanel accent="blue" className="p-0 overflow-hidden">
      {/* Receipt header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06] bg-white/[0.02]"
      >
        <div className="flex items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400"
          >
            <FileCheck className="h-4 w-4" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white"
            >Settlement Receipt</h2>
            <p className="text-[11px] text-slate-500"
            >
              Generated by AgentCFO ·{" "}
              {new Date(report.timestamp).toLocaleString("zh-CN")}
            </p>
          </div>
        </div>
        <StatusPill status="info">Audit</StatusPill>
      </div>

      <div className="p-5">
        <p className="text-sm text-slate-300 leading-relaxed">{report.summary}</p>

        {/* Stats grid */}
        <div className="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-3"
        >
          <div className="rounded-xl border border-emerald-500/15 bg-emerald-500/[0.04] px-4 py-4 text-center"
          >
            <p className="text-2xl font-bold text-emerald-400 font-mono-numbers"
            >{approvedCount}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-emerald-400/70"
            >Approved</p>
          </div>
          <div className="rounded-xl border border-red-500/15 bg-red-500/[0.04] px-4 py-4 text-center"
          >
            <p className="text-2xl font-bold text-red-400 font-mono-numbers"
            >{blockedCount}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-red-400/70"
            >Blocked</p>
          </div>
          <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] px-4 py-4 text-center"
          >
            <p className="text-2xl font-bold text-white font-mono-numbers"
            >{plan.totalAmount}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-slate-500"
            >Planned USDC</p>
          </div>
          <div className="rounded-xl border border-blue-500/15 bg-blue-500/[0.04] px-4 py-4 text-center"
          >
            <p className="text-2xl font-bold text-blue-400 font-mono-numbers"
            >{totalExecuted}</p>
            <p className="mt-1 text-[10px] font-medium uppercase tracking-wider text-blue-400/70"
            >Executed USDC</p>
          </div>
        </div>

        {/* Summary sections */}
        <div className="mt-5 space-y-2.5"
        >
          <div className="flex items-start gap-3 rounded-xl border border-emerald-500/15 bg-emerald-500/[0.04] px-4 py-3"
          >
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400"
            >
              <CheckCircle className="h-3.5 w-3.5" />
            </div>
            <div>
              <p className="text-sm font-semibold text-emerald-300"
              >Execution Summary</p>
              <p className="mt-0.5 text-xs leading-relaxed text-emerald-400/70"
              >
                {approvedCount} simulated transactions processed on Base Sepolia
                testnet. All payouts verified against AgentCFO treasury policy.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 rounded-xl border border-red-500/15 bg-red-500/[0.04] px-4 py-3"
          >
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-red-500/10 text-red-400"
            >
              <AlertTriangle className="h-3.5 w-3.5" />
            </div>
            <div>
              <p className="text-sm font-semibold text-red-300"
              >Risk Summary</p>
              <p className="mt-0.5 text-xs leading-relaxed text-red-400/70"
              >
                Whitelist check blocked {blockedCount} recipient
                {blockedCount > 1 ? "s" : ""}.{" "}
                {report.riskCheck.checks.whitelistCheck.reason}. Blocked amount:{" "}
                {blockedAmount} USDC. No funds were transferred for blocked
                items.
              </p>
            </div>
          </div>
        </div>

        {/* Receipt footer */}
        <div className="mt-5 border-t border-dashed border-white/10 pt-4"
        >
          <div className="flex items-center justify-between"
          >
            <div>
              <p className="text-[10px] font-medium uppercase tracking-wider text-slate-600"
              >Approved by</p>
              <p className="mt-0.5 text-sm font-medium text-slate-300"
              >{report.approvedBy}</p>
            </div>
            <div className="text-right"
            >
              <p className="text-[10px] font-medium uppercase tracking-wider text-slate-600"
              >Permission boundary</p>
              <p className="mt-0.5 text-xs text-slate-500 font-mono-numbers"
              >
                budget:50 / singleLimit:25 / token:USDC
              </p>
            </div>
          </div>
        </div>

        {/* Mock disclaimer */}
        <div className="mt-4 rounded-lg border border-white/[0.04] bg-white/[0.02] px-3 py-2.5"
        >
          <p className="text-[11px] leading-relaxed text-slate-600"
          >
            This is a mock settlement receipt for demonstration purposes. No real
            treasury operation or blockchain transaction occurred.
          </p>
        </div>
      </div>
    </GlassPanel>
  );
}
